disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Dylan Joseph Roy-Leo"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"

[author]
name = "Dylan J. Roy-Leo"
email = "djroy@umass.edu"
# image = 
headline = "My personal blog"
bio = "A little about me"
links = [
    {github = "https://github.com/dylroy"}
]
