disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Dylan Joseph Roy-Leo"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"

["params.author"]
name = "Dylan J. Roy-Leo"
email = "djroy@umass.edu"
