[[main]]
none = "none"

[[main]]
name = "My Stats"
pageRef = "my_stats"
weight = 1

[[main]]
name = "Talks"
pageRef = "Talks"
weight = 2

[[main]]
name = "Research"
pageRef = "Research"
weight = 3

[[main]]
name = "Interests"
pageRef = "Interests"
weight = 4

[[main]]
name = "Math"
pageRef = "Math"
parent = "Interests"
weight = 1

[[main]]
name = "CV"
pageRef = "cv"
weight = 5

[[main]]
pre = "github"
url = "https://github.com/dylroy"
identifier = "6OMlrtvubh"
weight = 6

[[footer]]
none = "none"
